// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqyXAJWI9GpLDAdcayAxCJSix7lXSXy7c',
    appId: '1:519881573465:web:e653f660416475cfd59d48',
    messagingSenderId: '519881573465',
    projectId: 'application-chama',
    authDomain: 'application-chama.firebaseapp.com',
    storageBucket: 'application-chama.appspot.com',
    measurementId: 'G-YW94PB1M53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7mUGNJBwhPe7eYVNLdmDfRvYqUvQ-MYU',
    appId: '1:519881573465:android:1cc6a22d7a7a6969d59d48',
    messagingSenderId: '519881573465',
    projectId: 'application-chama',
    storageBucket: 'application-chama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWvOl4EZeQSwgVcxV4WZ-vreC28CLsL4g',
    appId: '1:519881573465:ios:e93c381525e71d4ed59d48',
    messagingSenderId: '519881573465',
    projectId: 'application-chama',
    storageBucket: 'application-chama.appspot.com',
    iosBundleId: 'com.example.chama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWvOl4EZeQSwgVcxV4WZ-vreC28CLsL4g',
    appId: '1:519881573465:ios:e93c381525e71d4ed59d48',
    messagingSenderId: '519881573465',
    projectId: 'application-chama',
    storageBucket: 'application-chama.appspot.com',
    iosBundleId: 'com.example.chama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqyXAJWI9GpLDAdcayAxCJSix7lXSXy7c',
    appId: '1:519881573465:web:c29fab9cb88f0530d59d48',
    messagingSenderId: '519881573465',
    projectId: 'application-chama',
    authDomain: 'application-chama.firebaseapp.com',
    storageBucket: 'application-chama.appspot.com',
    measurementId: 'G-DK6076NR2L',
  );
}
